jobs:
- job: build
  pool:
    name: Default
  variables:  
    YARN_CACHE_FOLDER: $(Pipeline.Workspace)/yarn-cache
  steps:
  - task: RestoreCache@0
    inputs:
      key: '$(Build.SourcesDirectory)/yarn.lock'
      path: '$(YARN_CACHE_FOLDER)'

  - script: yarn
    displayName: 'Install dependencies'

#  - script: yarn build
#    displayName: 'Build and test'



  - task: SaveCache@0
    inputs:
      key: '$(Build.SourcesDirectory)/yarn.lock'
      path: '$(YARN_CACHE_FOLDER)'
