parameters:
  id: ''
  description: ''
  artifactName: ''
  itermPattern: ''

jobs:
- job: ${{ parameters.id }}
  variables:
    TEST_DESCRIPTION: ${{ parameters.description }}
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      downloadPath: '$(Build.SourcesDirectory)/results'
      artifactName: ${{ parameters.artifactName }}
      itemPattern: ${{ parameters.itemPattern }}
    continueOnError: true
  
  - bash: |
      echo "======================================================="
      echo "All artifacts:"
      cd files && grep -r -l "." | sort
      echo "======================================================="
      echo "Downloaded artifacts (${TEST_DESCRIPTION}):"
      cd ../results && grep -r -l "." | sort
      echo "======================================================="
    displayName: '${{ parameters.description }}'
    continueOnError: true