parameters:
  id: ''
  #description: ''
  artifactName: ''
  itermPattern: ''

jobs:
- job: ${{ parameters.id }}
  variables:
    TEST_DESCRIPTION: ${{ parameters.description }}
    ARTIFACT: ${{ parameters.artifactName }}
    PATTERN: ${{ parameters.itemPattern }}
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      downloadPath: '$(Build.SourcesDirectory)/results'
      artifactName: '$(ARTIFACT)'
      itemPattern: '$(PATTERN)'
    continueOnError: true
  
  - bash: |
      echo "======================================================="
      echo "All artifacts:"
      cd files && grep -r -l "." | sort
      echo "======================================================="
      echo "Downloaded artifacts (${ARTIFACT} ${PATTERN}):"
      cd ../results && grep -r -l "." | sort
      echo "======================================================="
    displayName: 'Results'
    continueOnError: true