parameters:
  id: ''
  artifactName: ''
  itermPattern: ''

jobs:
- job: ${{ parameters.id }}
  variables:
    TEST_DESCRIPTION: ${{ parameters.description }}
    ARTIFACT: ${{ parameters.artifactName }}
    PATTERN: ${{ parameters.itemPattern }}
  steps:
  - bash: |
      export DPA_ARTIFACT=${ARTIFACT}
      export DPA_PATTERN=${PATTERN}

      export DBA_ARTIFACT=${ARTIFACT/a/b}
      export DBA_PATTERN=${PATTERN/a/b}

      if [ -z "$DBA_ARTIFACT" ]; then
        export DBA_DOWNLOAD_TYPE="specific"
      else
        export DBA_DOWNLOAD_TYPE="single"
      fi

      echo "##vso[task.setVariable variable=DPA_ARTIFACT]$DPA_ARTIFACT"
      echo "##vso[task.setVariable variable=DPA_PATTERN]$DPA_PATTERN"
      echo "##vso[task.setVariable variable=DBA_ARTIFACT]$DBA_ARTIFACT"
      echo "##vso[task.setVariable variable=DBA_PATTERN]$DBA_PATTERN"
      echo "##vso[task.setVariable variable=DBA_DOWNLOAD_TYPE]$DBA_DOWNLOAD_TYPE"

  - task: DownloadBuildArtifacts@0
    inputs:
      downloadPath: '$(Build.SourcesDirectory)/results/dba'
      artifactName: '$(DBA_ARTIFACT)'
      itemPattern: '$(DBA_PATTERN)'
      downloadType: '$(DBA_DOWNLOAD_TYPE)'
    continueOnError: true

  - task: DownloadPipelineArtifact@1
    inputs:
      targetPath: '$(Build.SourcesDirectory)/results/dpa'
      ArtifactName: '$(DPA_ARTIFACT)'
      itemPattern: '$(DPA_PATTERN)'
    continueOnError: true    
  
  - bash: |
      echo "======================================================="
      echo "All artifacts:"
      cd files
      grep -r -l "." | sort
      mv a1 b1
      mv a2 b2
      mv a3 b3
      grep -r -l "." | sort
      echo "======================================================="
      echo "DBA (artifact=${DBA_ARTIFACT}, pattern=${DBA_PATTERN}):"
      cd ../results/dba/ && grep -r -l "." | sort
      echo "======================================================="
      echo "DPA (artifact=${DPA_ARTIFACT}, pattern=${DPA_PATTERN}):"
      cd ../results/dpa/ && grep -r -l "." | sort
    displayName: 'Results'
    continueOnError: true